#!/bin/bash

# Compile the main program.
mkdir -p out
clang -O3 -Wall -Wextra -Werror -Wpedantic -o out/main main.c

# Use the program to generate the code.
./out/main > ./out/gen.c
# Run clang-format so we can look at the generated code in all its glory.
clang-format -i ./out/gen.c

# Compile and run it.
clang -o ./out/gen ./out/gen.c
./out/gen
